# Generated by Django 3.1.3 on 2021-01-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcalendar', '0002_auto_20210131_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match2',
            new_name='Match',
        ),
    ]
