# Generated by Django 3.1.3 on 2021-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default=0, upload_to='players_photos'),
            preserve_default=False,
        ),
    ]
