# Generated by Django 3.1.3 on 2021-01-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_player_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
