# Generated by Django 3.1.3 on 2021-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_auto_20210129_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='no_photo.png', upload_to='images/players_photos'),
        ),
    ]
