# Generated by Django 3.1.3 on 2021-01-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_auto_20210129_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pm',
            field=models.IntegerField(blank=True),
        ),
    ]
