# Generated by Django 3.1.3 on 2021-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_auto_20210129_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
