# Generated by Django 3.1.3 on 2021-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_auto_20210129_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pm',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
