# Generated by Django 3.1.3 on 2021-01-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_auto_20210129_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='passes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='pm',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
