# Generated by Django 3.1.3 on 2021-02-01 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_auto_20210129_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(default='100', max_length=3),
        ),
    ]
